FROM python:3.11-slim

RUN apt-get update && apt-get install -y git python3-pip

WORKDIR /root

RUN git clone https://github.com/GabrielAlves/Prototipo1.git src

WORKDIR /root/src/frontend

ENV BACKEND_API_BASE 'http://localhost:8002'

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5001

CMD ["python", "app.py"]