services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      retries: 10
      start_period: 15s
      timeout: 5s

  backend:
    build: ./backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+mysqlconnector://admin:admin@db:3306/db
    ports:
      - "8002:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://backend:8000
    ports:
      - "5003:5001"
    volumes:
      - ./frontend:/app

volumes:
  db_data: